spring:
  profiles:
    active: .
  application:
    name: shili-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/mysl?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    # &serverTimezone=GMT%2B8 org.apache.ibatis.session
    username: root
    password: root
  mvc:
    # 静态文件请求匹配方式
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/,
        - classpath:/resources/,
        - classpath:/static/,
        - classpath:/public/,
        - classpath:/os/
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
  jackson:
    property-naming-strategy: SNAKE_CASE
springfox:
  documentation:
    swagger-ui:
      enabled: false
mybatis-plus:
  mapper-locations: com/mysl/api/mapper/xml/*.xml
  global-config:
    banner: false
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
easylog:
  banner: false
server:
  port: 3001
logging:
  config: classpath:log4j2.xml
mysl:
  jwt:
    key: a1b2c3
    expiration: 86400
    login:
      distance-limit: 100
      location-check: false
      time-check: false
    tencent:
      api:
        secretId:
        secretKey:
      cos:
        endpoint:
        bucketName:
        region:
    open:
      wx:
        xcx-id:
        xcx-secret:
